# Generated by Django 4.0.6 on 2022-08-02 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('l_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('nick', models.CharField(max_length=20, verbose_name='User Nick')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Venue Name')),
                ('city', models.CharField(max_length=60, verbose_name='Venue City')),
                ('address', models.CharField(max_length=120)),
                ('zip', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20, verbose_name='Venue Phone')),
                ('web', models.URLField(verbose_name='Venue Web')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Event Name')),
                ('event_date', models.DateTimeField(verbose_name='Event Date')),
                ('manager', models.CharField(max_length=60)),
                ('desciption', models.TextField(blank=True)),
                ('participants', models.ManyToManyField(blank=True, to='events.user')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.venue')),
            ],
        ),
    ]
