# Generated by Django 4.0.6 on 2022-08-04 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_user_web_user_alter_event_manager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Web_User',
            new_name='WebUser',
        ),
    ]
