# Generated by Django 4.0.6 on 2022-08-05 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_web_user_webuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='zip',
            new_name='province',
        ),
    ]
