# Generated by Django 4.0.6 on 2022-08-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_zip_venue_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='province',
            field=models.CharField(max_length=20),
        ),
    ]
