# Generated by Django 4.0.6 on 2022-08-13 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0015_venue_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='venue',
            name='owner',
            field=models.ForeignKey(default=None, max_length=60, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='web',
            field=models.URLField(blank=True, max_length=60, verbose_name='Venue Web'),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='email',
            field=models.EmailField(max_length=40, unique=True),
        ),
    ]
