# Generated by Django 4.0.6 on 2022-08-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_alter_venue_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webuser',
            name='email',
            field=models.EmailField(max_length=40, unique=True, verbose_name='User Email'),
        ),
    ]
