# Generated by Django 4.0.6 on 2022-08-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_alter_webuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webuser',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='User Phone'),
        ),
    ]
