# Generated by Django 4.0.6 on 2022-08-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_alter_webuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=600, verbose_name='Event Description'),
        ),
    ]
