# Generated by Django 4.0.6 on 2022-08-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_alter_event_manager_alter_venue_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/', verbose_name='Event Image'),
        ),
    ]
