# Generated by Django 4.0.6 on 2022-08-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_alter_event_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(default='images/Tradeshow.png', upload_to='images/', verbose_name='Event Image'),
        ),
    ]
