# Generated by Django 4.0.6 on 2022-08-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_alter_event_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Confirmation'),
        ),
    ]
