# Generated by Django 4.0.6 on 2022-08-26 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_alter_event_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_date', 'venue']},
        ),
    ]
