# Generated by Django 4.0.6 on 2022-08-26 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['name', 'city']},
        ),
    ]
