# Generated by Django 4.0.6 on 2022-08-26 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_alter_event_options_alter_venue_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_date', 'venue']},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['name', 'city']},
        ),
    ]
