from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('calendar', views.see_calendar, name="see-calendar"),
    path('calendar/<int:year>/<str:month>', views.see_calendar, name="see-calendar"),
    path('this_month', views.this_month, name="this-month"),
    path('next', views.next, name="next"),
    path('events', views.all_events, name="events_all"),
    path('add_venue', views.add_venue, name="add-venue"),
    path('my_venues', views.my_venues, name="my-venues"),
    path('add_event', views.add_event, name="add-event"),
    path('my_events', views.my_events, name="my-events"),
    path('list_venues', views.list_venues, name="list-venues"),
    path('show_venue/<venue_id>', views.show_venue, name="show-venue"),
    path('show_event/<event_id>', views.show_event, name="show-event"),
    path('mod_event/<event_id>', views.mod_event, name="mod-event"),
    path('del_event/<event_id>', views.del_event, name="del-event"),
    path('search', views.search, name="search"),
    path('check_date', views.check_date, name="check-date"),
    path('admin_approve', views.admin_approve, name="admin-approve"),
    path('statistics', views.statistics, name="statistics"),
    path('upcoming_events', views.upcoming_events, name="upcoming-events"),
    path('on_hold_events', views.on_hold_events, name="on-hold-events"),
    path('past_events', views.past_events, name="past-events"),
    path('active_venues', views.active_venues, name="active-venues"),
    path('on_hold_venues', views.on_hold_venues, name="on-hold-venues"),
    path('venue_owners', views.venue_owners, name="venue-owners"),
    path('event_managers', views.event_managers, name="event-managers"),
    path('owner_venues/<look_owner>', views.owner_venues, name="owner-venues"),
    path('venue_events/<venue_id>', views.venue_events, name="venue-events"),
    path('join_event/<event_id>', views.join_event, name= "join-event"),
    path('leave_event/<event_id>', views.leave_event, name= "leave-event"),
]
